sudo: false
language: node_js
node_js:
  - '0.12'
notifications:
  email: false
deploy:
  provider: npm
  email: rishabhsrao@gmail.com
  on:
    tags: true
  api_key:
    secure: ct8YCCsrM74zipKL3JaysslefxdYWmOQfEU0Hu04M7auwQ9sEQhmlBZ3D75WX3+K8WYaghJyxEuLTMxpGTx/nXmqLe1rkR9JqEQXAkqEsNnao3BYOmgy05xUennBlSjYPAGGZ7wYVS1QsIoGKq/4ka9Uf7OOPtyq6it8Vwu7sygduVCDZgdOP+/gayJDzuLMSk5xw9XF3vvP9ndh5X43U9FU87SPF4o6uJn2sYTkH6LVwwq+Ywam9xJUOZcgS5T6x6yzwSdtBbXAS4cyyhc4xG8vyfP1x3SuI5UHXbX9P73EvAVvI4m1tEP5nKV+KDlztLWP+NPTfETo+B+8WIHLklyqqdqew2KDQspp1hlv720HHekA0ke4bL7mBLepRgkDugKYEnDV5p/TSitGhyyc8wseMBMnGFM66rFwxhzx/cT6ME/3sNRoRD3oj2fcPvl+jskNyJyYz75f1PS59RVkP3WtFopadLGGzvByELY2ZgMNL9uzUNSpqzUn7HerADxmmV/s3EChqPDSboYZC6PwN1FEpULuEmb39FIng8Tnq+OMEHlKo/qY5oGWsP7POHsrQItj1G/bkzNYxxd138vwCErizLDZ23Uq+r6vC78O6hoze13krDOj7L8k2awugK0ux5IfSciHO47JaDPO3/IosjjL+isS++RBrq6khKZ4aUc=
